@startuml Diagrama_de_Estados_Bus
skinparam defaultTextAlignment center

[*] --> EmpezarRuta

state EmpezarRuta {
  [*] --> SubidaConductor : "Conductor sube"
  SubidaConductor --> ConfiguracionRuta : "Configura la ruta"
  ConfiguracionRuta --> VerificacionHorario : "Verifica el horario"
  VerificacionHorario --> Salida : "Sale de la sede de buses"
  Salida --> IniciaRuta
  IniciaRuta --> Parada
  Parada --> RecogePasajeros : "Recoge pasajeros"
  RecogePasajeros --> DejaPasajeros : "Deja pasajeros"
  DejaPasajeros --> Parada : "Siguiente parada"
  Parada --> FinDeRuta : "Fin de la ruta"
  FinDeRuta --> Regreso
  Regreso --> IniciaRuta
  Regreso --> TerminaHorario : "Regresa la sede de buses y finaliza el día"
  TerminaHorario --> [*]
}

@enduml
